### ISSUE TITLE
Platformio: Adding Arduino in component folder is not needed

### ISSUE THREAD

**Issue by Jason2866** [ricardoquesada/esp-idf-arduino-bluepad32-template#7]
this is done by Platformio "behind" the scenes already.

**Comment by ricardoquesada** [comment]
Thanks. 
I still need the "arduino" component for folks that don't want to use platformio and prefer to use `idf.py` directly.

**Comment by Jason2866** [comment]
Imho you should separate the two ways to build. The Platformio setup how it is currently, is weird. Loosing the greatest benefit from Platformio.

**Comment by ricardoquesada** [comment]
Thanks.
For mantainance purposes, I'd like that both builders use the same source code.

I realized that I don't need to put the `arduino` in the `#framework = arduino, espidf` since I'm providing the source code for it.

Thanks for the help!
